In [7]:
import pandas as pd
import numpy as np

In [8]:
brasileirao = pd.read_excel('brasileirao2023.xlsx')
brasileirao

Temporada  Rodada Mandante  Score_m Visitante  Score_v
0         2023       1      PAL      2.0       CUI      1.0
1         2023       1      AME      0.0       FLU      3.0
2         2023       1      CAP      2.0       GOI      0.0
3         2023       1      BOT      2.0       SAO      1.0
4         2023       1      RED      2.0       BAH      1.0
..         ...     ...      ...      ...       ...      ...
375       2023      38      GOI      NaN       AME      NaN
376       2023      38      SAN      NaN       FOR      NaN
377       2023      38      SAO      NaN       FLA      NaN
378       2023      38      VAS      NaN       RED      NaN
379       2023      38      FLU      NaN       GRE      NaN

[380 rows x 6 columns]

In [9]:
brasileirao = brasileirao[brasileirao['Score_m'].notnull()]
brasileirao

Temporada  Rodada Mandante  Score_m Visitante  Score_v
0        2023       1      PAL      2.0       CUI      1.0
1        2023       1      AME      0.0       FLU      3.0
2        2023       1      CAP      2.0       GOI      0.0
3        2023       1      BOT      2.0       SAO      1.0
4        2023       1      RED      2.0       BAH      1.0
5        2023       1      FOR      1.0       INT      1.0
6        2023       1      CAM      1.0       VAS      2.0
7        2023       1      COR      2.0       CRU      1.0
8        2023       1      FLA      3.0       CFC      0.0
9        2023       1      GRE      1.0       SAN      0.0
10       2023       2      FLU      2.0       CAP      0.0
11       2023       2      CUI      1.0       RED      1.0
12       2023       2      SAO      3.0       AME      0.0
13       2023       2      CRU      1.0       GRE      0.0
14       2023       2      INT      2.0       FLA      1.0
15       2023       2      VAS      2.0       PAL      2.0
16       2023       2      SAN      0.0       CAM      0.0
17       2023       2      CFC      0.0       FOR      3.0
18       2023       2      GOI      3.0       COR      1.0
19       2023       2      BAH      1.0       BOT      2.0
20       2023       3      FOR      4.0       FLU      2.0
21       2023       3      CFC      1.0       SAO      1.0
22       2023       3      PAL      2.0       COR      1.0
23       2023       3      RED      0.0       CRU      3.0
24       2023       3      SAN      3.0       AME      2.0
25       2023       3      CAM      2.0       CAP      1.0
26       2023       3      FLA      2.0       BOT      3.0
27       2023       3      INT      1.0       GOI      0.0
28       2023       3      CUI      1.0       GRE      2.0
29       2023       3      VAS      0.0       BAH      1.0
30       2023       4      CRU      2.0       SAN      1.0
31       2023       4      FLU      1.0       VAS      1.0
32       2023       4      AME      1.0       CUI      2.0
33       2023       4      BAH      3.0       CFC      1.0
34       2023       4      CAP      2.0       FLA      1.0
35       2023       4      SAO      2.0       INT      0.0
36       2023       4      GRE      3.0       RED      3.0
37       2023       4      BOT      2.0       CAM      0.0
38       2023       4      GOI      0.0       PAL      5.0
39       2023       4      COR      1.0       FOR      1.0
40       2023       5      SAN      3.0       BAH      0.0
41       2023       5      RED      2.0       AME      2.0
42       2023       5      INT      0.0       CAP      2.0
43       2023       5      CUI      0.0       CAM      4.0
44       2023       5      FLA      2.0       GOI      0.0
45       2023       5      PAL      4.0       GRE      1.0
46       2023       5      CRU      0.0       FLU      2.0
47       2023       5      CFC      1.0       VAS      1.0
48       2023       5      BOT      3.0       COR      0.0
49       2023       5      FOR      0.0       SAO      0.0
50       2023       6      BAH      2.0       FLA      3.0
51       2023       6      PAL      1.0       RED      1.0
52       2023       6      FLU      2.0       CUI      0.0
53       2023       6      CAM      2.0       INT      0.0

In [10]:
times = brasileirao['Mandante'].unique()
tabela = pd.DataFrame()
for time in times:
    vit = emp = der = pro = con = jog = 0
    # emp = 0
    # der = 0
    # pro = 0
    # con = 0
    # jog = 0
    mandante = brasileirao[brasileirao['Mandante'] == time]
    for indice, partida in mandante.iterrows():
        if partida['Score_m'] > partida['Score_v']:
            vit += 1 
        elif partida['Score_m'] == partida['Score_v']:
            emp += 1
        else:
            der += 1
        pro += partida['Score_m']
        con += partida['Score_v']
        jog += 1
    visitante = brasileirao[brasileirao['Visitante'] == time]
    for indice, partida in visitante.iterrows():
        if partida['Score_v'] > partida['Score_m']:
            vit += 1
        elif partida['Score_v'] == partida['Score_m']:
            emp += 1
        else:
            der += 1
        pro += partida['Score_v']
        con += partida['Score_m']
        jog += 1
    new_row = pd.DataFrame({
        '1-Time': [time],
        '3-J': [jog],
        '4-V': [vit],
        '5-E' : [emp],
        '6-D': [der],
        '7-GP': [pro],
        '8-GC': [con]
    })   
    tabela = pd.concat([tabela, new_row], ignore_index = True)
    
tabela['2-P'] = (tabela['4-V'] * 3) + tabela['5-E']
tabela['9-SG'] = tabela['7-GP'] - tabela['8-GC']   
tabela_sort = tabela.sort_values(by=['2-P','4-V','9-SG'], ascending=False)
tabela_sort

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG
3     BOT    5    5    0    0  12.0   4.0   15   8.0
0     PAL    6    4    2    0  16.0   6.0   14  10.0
10    FLU    6    4    1    1  12.0   5.0   13   7.0
6     CAM    6    3    1    2   9.0   5.0   10   4.0
8     FLA    6    3    0    3  12.0   9.0    9   3.0
2     CAP    5    3    0    2   7.0   5.0    9   2.0
13    CRU    5    3    0    2   7.0   5.0    9   2.0
5     FOR    5    2    3    0   9.0   4.0    9   5.0
12    SAO    5    2    2    1   7.0   3.0    8   4.0
16    SAN    5    2    1    2   7.0   5.0    7   2.0
9     GRE    5    2    1    2   7.0   9.0    7  -2.0
14    INT    6    2    1    3   4.0   8.0    7  -4.0
4     RED    6    1    4    1   9.0  11.0    7  -2.0
19    BAH    6    2    0    4   8.0  11.0    6  -3.0
15    VAS    5    1    3    1   6.0   6.0    6   0.0
7     COR    5    1    1    3   5.0  10.0    4  -5.0
11    CUI    6    1    1    4   5.0  12.0    4  -7.0
18    GOI    5    1    0    4   3.0  11.0    3  -8.0
17    CFC    5    0    2    3   3.0  11.0    2  -8.0
1     AME    5    0    1    4   5.0  13.0    1  -8.0

In [11]:
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG
0     PAL    6    4    2    0  16.0   6.0   14  10.0
1     AME    5    0    1    4   5.0  13.0    1  -8.0
2     CAP    5    3    0    2   7.0   5.0    9   2.0
3     BOT    5    5    0    0  12.0   4.0   15   8.0
4     RED    6    1    4    1   9.0  11.0    7  -2.0
5     FOR    5    2    3    0   9.0   4.0    9   5.0
6     CAM    6    3    1    2   9.0   5.0   10   4.0
7     COR    5    1    1    3   5.0  10.0    4  -5.0
8     FLA    6    3    0    3  12.0   9.0    9   3.0
9     GRE    5    2    1    2   7.0   9.0    7  -2.0
10    FLU    6    4    1    1  12.0   5.0   13   7.0
11    CUI    6    1    1    4   5.0  12.0    4  -7.0
12    SAO    5    2    2    1   7.0   3.0    8   4.0
13    CRU    5    3    0    2   7.0   5.0    9   2.0
14    INT    6    2    1    3   4.0   8.0    7  -4.0
15    VAS    5    1    3    1   6.0   6.0    6   0.0
16    SAN    5    2    1    2   7.0   5.0    7   2.0
17    CFC    5    0    2    3   3.0  11.0    2  -8.0
18    GOI    5    1    0    4   3.0  11.0    3  -8.0
19    BAH    6    2    0    4   8.0  11.0    6  -3.0

In [12]:
from sklearn.cluster import KMeans
df_data = tabela[[
    '2-P',              
    '4-V',
    '5-E',
    '6-D',
    '9-SG'
]]
kmeans = KMeans(n_clusters=5, random_state=0).fit(df_data)
tabela['cluster'] = kmeans.labels_
# tabela['c_p'] = kmeans.cluster_centers_[kmeans.labels_,0]
# tabela['c_v'] = kmeans.cluster_centers_[kmeans.labels_,1]
# tabela['c_e'] = kmeans.cluster_centers_[kmeans.labels_,2]
# tabela['c_d'] = kmeans.cluster_centers_[kmeans.labels_,3]
# tabela['c_sg'] = kmeans.cluster_centers_[kmeans.labels_,4]
tabela

c:\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster
0     PAL    6    4    2    0  16.0   6.0   14  10.0        2
1     AME    5    0    1    4   5.0  13.0    1  -8.0        1
2     CAP    5    3    0    2   7.0   5.0    9   2.0        0
3     BOT    5    5    0    0  12.0   4.0   15   8.0        2
4     RED    6    1    4    1   9.0  11.0    7  -2.0        3
5     FOR    5    2    3    0   9.0   4.0    9   5.0        0
6     CAM    6    3    1    2   9.0   5.0   10   4.0        0
7     COR    5    1    1    3   5.0  10.0    4  -5.0        1
8     FLA    6    3    0    3  12.0   9.0    9   3.0        0
9     GRE    5    2    1    2   7.0   9.0    7  -2.0        4
10    FLU    6    4    1    1  12.0   5.0   13   7.0        2
11    CUI    6    1    1    4   5.0  12.0    4  -7.0        1
12    SAO    5    2    2    1   7.0   3.0    8   4.0        0
13    CRU    5    3    0    2   7.0   5.0    9   2.0        0
14    INT    6    2    1    3   4.0   8.0    7  -4.0        4
15    VAS    5    1    3    1   6.0   6.0    6   0.0        3
16    SAN    5    2    1    2   7.0   5.0    7   2.0        0
17    CFC    5    0    2    3   3.0  11.0    2  -8.0        1
18    GOI    5    1    0    4   3.0  11.0    3  -8.0        1
19    BAH    6    2    0    4   8.0  11.0    6  -3.0        4

In [13]:
print(kmeans.labels_)

[2 1 0 2 3 0 0 1 0 4 2 1 0 0 4 3 0 1 1 4]


In [14]:
kmeans.cluster_centers_

array([[ 8.71428571,  2.57142857,  1.        ,  1.71428571,  3.14285714],
       [ 2.8       ,  0.6       ,  1.        ,  3.6       , -7.2       ],
       [14.        ,  4.33333333,  1.        ,  0.33333333,  8.33333333],
       [ 6.5       ,  1.        ,  3.5       ,  1.        , -1.        ],
       [ 6.66666667,  2.        ,  0.66666667,  3.        , -3.        ]])

In [15]:
df_cluster = pd.DataFrame()
for cluster, colunas in enumerate(kmeans.cluster_centers_):
    print(cluster)
    print(colunas)
    new_row = pd.DataFrame({
        'cluster': [cluster], 
        '2-P': [colunas[0]],              
        '4-V': [colunas[1]],
        '5-E': [colunas[2]],
        '6-D': [colunas[3]],
        '9-SG': [colunas[4]],
    })
    df_cluster = pd.concat([df_cluster, new_row], ignore_index=True)
df_cluster

0
[8.71428571 2.57142857 1.         1.71428571 3.14285714]
1
[ 2.8  0.6  1.   3.6 -7.2]
2
[14.          4.33333333  1.          0.33333333  8.33333333]
3
[ 6.5  1.   3.5  1.  -1. ]
4
[ 6.66666667  2.          0.66666667  3.         -3.        ]


cluster        2-P       4-V       5-E       6-D      9-SG
0        0   8.714286  2.571429  1.000000  1.714286  3.142857
1        1   2.800000  0.600000  1.000000  3.600000 -7.200000
2        2  14.000000  4.333333  1.000000  0.333333  8.333333
3        3   6.500000  1.000000  3.500000  1.000000 -1.000000
4        4   6.666667  2.000000  0.666667  3.000000 -3.000000

In [16]:
df_cluster_sort = df_cluster.sort_values(by='2-P', ascending=False)
df_cluster_sort

cluster        2-P       4-V       5-E       6-D      9-SG
2        2  14.000000  4.333333  1.000000  0.333333  8.333333
0        0   8.714286  2.571429  1.000000  1.714286  3.142857
4        4   6.666667  2.000000  0.666667  3.000000 -3.000000
3        3   6.500000  1.000000  3.500000  1.000000 -1.000000
1        1   2.800000  0.600000  1.000000  3.600000 -7.200000

In [17]:
df_cluster_sort['grupo'] = ['Titulo','Libertadores','Sul-Americana','limbo','Rebaixamento']
df_cluster_sort

cluster        2-P       4-V       5-E       6-D      9-SG          grupo
2        2  14.000000  4.333333  1.000000  0.333333  8.333333         Titulo
0        0   8.714286  2.571429  1.000000  1.714286  3.142857   Libertadores
4        4   6.666667  2.000000  0.666667  3.000000 -3.000000  Sul-Americana
3        3   6.500000  1.000000  3.500000  1.000000 -1.000000          limbo
1        1   2.800000  0.600000  1.000000  3.600000 -7.200000   Rebaixamento

In [18]:
df_cluster_grupo = df_cluster_sort[['cluster','grupo']]
df_cluster_grupo

cluster          grupo
2        2         Titulo
0        0   Libertadores
4        4  Sul-Americana
3        3          limbo
1        1   Rebaixamento

In [19]:
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster
0     PAL    6    4    2    0  16.0   6.0   14  10.0        2
1     AME    5    0    1    4   5.0  13.0    1  -8.0        1
2     CAP    5    3    0    2   7.0   5.0    9   2.0        0
3     BOT    5    5    0    0  12.0   4.0   15   8.0        2
4     RED    6    1    4    1   9.0  11.0    7  -2.0        3
5     FOR    5    2    3    0   9.0   4.0    9   5.0        0
6     CAM    6    3    1    2   9.0   5.0   10   4.0        0
7     COR    5    1    1    3   5.0  10.0    4  -5.0        1
8     FLA    6    3    0    3  12.0   9.0    9   3.0        0
9     GRE    5    2    1    2   7.0   9.0    7  -2.0        4
10    FLU    6    4    1    1  12.0   5.0   13   7.0        2
11    CUI    6    1    1    4   5.0  12.0    4  -7.0        1
12    SAO    5    2    2    1   7.0   3.0    8   4.0        0
13    CRU    5    3    0    2   7.0   5.0    9   2.0        0
14    INT    6    2    1    3   4.0   8.0    7  -4.0        4
15    VAS    5    1    3    1   6.0   6.0    6   0.0        3
16    SAN    5    2    1    2   7.0   5.0    7   2.0        0
17    CFC    5    0    2    3   3.0  11.0    2  -8.0        1
18    GOI    5    1    0    4   3.0  11.0    3  -8.0        1
19    BAH    6    2    0    4   8.0  11.0    6  -3.0        4

In [20]:
import matplotlib 

tabela_sort = tabela.sort_values(by=['2-P','4-V','9-SG'], ascending=False)
tabela_sort.style.background_gradient(cmap='Blues')
# tabela_sort.style.background_gradient(cmap='Blues').format("{:.2f}").render()
