In [1]:
import pandas as pd
import numpy as np
import streamlit as st

In [2]:
brasileirao = pd.read_excel('./data/brasileirao2023.xlsx')
brasileirao

Temporada  Rodada Mandante  Score_m Visitante  Score_v
0         2023       1      PAL      2.0       CUI      1.0
1         2023       1      AME      0.0       FLU      3.0
2         2023       1      CAP      2.0       GOI      0.0
3         2023       1      BOT      2.0       SAO      1.0
4         2023       1      RED      2.0       BAH      1.0
..         ...     ...      ...      ...       ...      ...
375       2023      38      GOI      NaN       AME      NaN
376       2023      38      SAN      NaN       FOR      NaN
377       2023      38      SAO      NaN       FLA      NaN
378       2023      38      VAS      NaN       RED      NaN
379       2023      38      FLU      NaN       GRE      NaN

[380 rows x 6 columns]

In [3]:
brasileirao = brasileirao[brasileirao['Score_m'].notnull()]
brasileirao

Temporada  Rodada Mandante  Score_m Visitante  Score_v
0         2023       1      PAL      2.0       CUI      1.0
1         2023       1      AME      0.0       FLU      3.0
2         2023       1      CAP      2.0       GOI      0.0
3         2023       1      BOT      2.0       SAO      1.0
4         2023       1      RED      2.0       BAH      1.0
..         ...     ...      ...      ...       ...      ...
175       2023      18      GOI      1.0       FOR      0.0
176       2023      18      CRU      0.0       BOT      0.0
177       2023      18      INT      2.0       COR      2.0
178       2023      18      CFC      0.0       RED      1.0
179       2023      18      CUI      3.0       FLA      0.0

[180 rows x 6 columns]

In [4]:
times = brasileirao['Mandante'].unique()
tabela = pd.DataFrame()
for time in times:
    vit = emp = der = pro = con = jog = 0
    # emp = 0
    # der = 0
    # pro = 0
    # con = 0
    # jog = 0
    mandante = brasileirao[brasileirao['Mandante'] == time]
    for indice, partida in mandante.iterrows():
        if partida['Score_m'] > partida['Score_v']:
            vit += 1 
        elif partida['Score_m'] == partida['Score_v']:
            emp += 1
        else:
            der += 1
        pro += partida['Score_m']
        con += partida['Score_v']
        jog += 1
    visitante = brasileirao[brasileirao['Visitante'] == time]
    for indice, partida in visitante.iterrows():
        if partida['Score_v'] > partida['Score_m']:
            vit += 1
        elif partida['Score_v'] == partida['Score_m']:
            emp += 1
        else:
            der += 1
        pro += partida['Score_v']
        con += partida['Score_m']
        jog += 1
    new_row = pd.DataFrame({
        '1-Time': [time],
        '3-J': [jog],
        '4-V': [vit],
        '5-E' : [emp],
        '6-D': [der],
        '7-GP': [pro],
        '8-GC': [con]
    })   
    tabela = pd.concat([tabela, new_row], ignore_index = True)
    
tabela['2-P'] = (tabela['4-V'] * 3) + tabela['5-E']
tabela['9-SG'] = tabela['7-GP'] - tabela['8-GC']   
tabela_sort = tabela.sort_values(by=['2-P','4-V','9-SG'], ascending=False)
tabela_sort

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG
3     BOT   18   14    2    2  32.0  10.0   44  22.0
8     FLA   18    9    4    5  30.0  23.0   31   7.0
10    FLU   18    9    4    5  24.0  17.0   31   7.0
9     GRE   18    9    4    5  26.0  22.0   31   4.0
0     PAL   18    8    7    3  33.0  17.0   31  16.0
4     RED   18    8    7    3  26.0  16.0   31  10.0
2     CAP   18    8    4    6  26.0  22.0   28   4.0
11    CUI   18    8    4    6  21.0  19.0   28   2.0
12    SAO   18    7    5    6  23.0  18.0   26   5.0
6     CAM   18    6    6    6  21.0  17.0   24   4.0
13    CRU   18    6    6    6  19.0  15.0   24   4.0
14    INT   18    6    6    6  16.0  20.0   24  -4.0
5     FOR   18    6    5    7  17.0  19.0   23  -2.0
7     COR   18    5    6    7  17.0  20.0   21  -3.0
18    GOI   18    5    4    9  17.0  27.0   19 -10.0
19    BAH   18    4    6    8  18.0  24.0   18  -6.0
16    SAN   18    4    6    8  19.0  27.0   18  -8.0
17    CFC   18    3    5   10  17.0  33.0   14 -16.0
15    VAS   18    3    4   11  13.0  28.0   13 -15.0
1     AME   18    2    5   11  19.0  40.0   11 -21.0

In [5]:
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG
0     PAL   18    8    7    3  33.0  17.0   31  16.0
1     AME   18    2    5   11  19.0  40.0   11 -21.0
2     CAP   18    8    4    6  26.0  22.0   28   4.0
3     BOT   18   14    2    2  32.0  10.0   44  22.0
4     RED   18    8    7    3  26.0  16.0   31  10.0
5     FOR   18    6    5    7  17.0  19.0   23  -2.0
6     CAM   18    6    6    6  21.0  17.0   24   4.0
7     COR   18    5    6    7  17.0  20.0   21  -3.0
8     FLA   18    9    4    5  30.0  23.0   31   7.0
9     GRE   18    9    4    5  26.0  22.0   31   4.0
10    FLU   18    9    4    5  24.0  17.0   31   7.0
11    CUI   18    8    4    6  21.0  19.0   28   2.0
12    SAO   18    7    5    6  23.0  18.0   26   5.0
13    CRU   18    6    6    6  19.0  15.0   24   4.0
14    INT   18    6    6    6  16.0  20.0   24  -4.0
15    VAS   18    3    4   11  13.0  28.0   13 -15.0
16    SAN   18    4    6    8  19.0  27.0   18  -8.0
17    CFC   18    3    5   10  17.0  33.0   14 -16.0
18    GOI   18    5    4    9  17.0  27.0   19 -10.0
19    BAH   18    4    6    8  18.0  24.0   18  -6.0

In [6]:
from sklearn.cluster import KMeans
df_data = tabela[[
    '2-P',              
    '4-V',
    '5-E',
    '6-D',
    '9-SG'
]]
kmeans = KMeans(n_clusters=5, random_state=0).fit(df_data)
tabela['cluster'] = kmeans.labels_
# tabela['c_p'] = kmeans.cluster_centers_[kmeans.labels_,0]
# tabela['c_v'] = kmeans.cluster_centers_[kmeans.labels_,1]
# tabela['c_e'] = kmeans.cluster_centers_[kmeans.labels_,2]
# tabela['c_d'] = kmeans.cluster_centers_[kmeans.labels_,3]
# tabela['c_sg'] = kmeans.cluster_centers_[kmeans.labels_,4]
tabela

c:\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster
0     PAL   18    8    7    3  33.0  17.0   31  16.0        2
1     AME   18    2    5   11  19.0  40.0   11 -21.0        0
2     CAP   18    8    4    6  26.0  22.0   28   4.0        1
3     BOT   18   14    2    2  32.0  10.0   44  22.0        4
4     RED   18    8    7    3  26.0  16.0   31  10.0        2
5     FOR   18    6    5    7  17.0  19.0   23  -2.0        3
6     CAM   18    6    6    6  21.0  17.0   24   4.0        1
7     COR   18    5    6    7  17.0  20.0   21  -3.0        3
8     FLA   18    9    4    5  30.0  23.0   31   7.0        1
9     GRE   18    9    4    5  26.0  22.0   31   4.0        1
10    FLU   18    9    4    5  24.0  17.0   31   7.0        1
11    CUI   18    8    4    6  21.0  19.0   28   2.0        1
12    SAO   18    7    5    6  23.0  18.0   26   5.0        1
13    CRU   18    6    6    6  19.0  15.0   24   4.0        1
14    INT   18    6    6    6  16.0  20.0   24  -4.0        3
15    VAS   18    3    4   11  13.0  28.0   13 -15.0        0
16    SAN   18    4    6    8  19.0  27.0   18  -8.0        3
17    CFC   18    3    5   10  17.0  33.0   14 -16.0        0
18    GOI   18    5    4    9  17.0  27.0   19 -10.0        3
19    BAH   18    4    6    8  18.0  24.0   18  -6.0        3

In [7]:
print(kmeans.labels_)

[2 0 1 4 2 3 1 3 1 1 1 1 1 1 3 0 3 0 3 3]


In [8]:
kmeans.cluster_centers_

array([[ 12.66666667,   2.66666667,   4.66666667,  10.66666667,
        -17.33333333],
       [ 27.875     ,   7.75      ,   4.625     ,   5.625     ,
          4.625     ],
       [ 31.        ,   8.        ,   7.        ,   3.        ,
         13.        ],
       [ 20.5       ,   5.        ,   5.5       ,   7.5       ,
         -5.5       ],
       [ 44.        ,  14.        ,   2.        ,   2.        ,
         22.        ]])

In [9]:
df_cluster = pd.DataFrame()
for cluster, colunas in enumerate(kmeans.cluster_centers_):
    print(cluster)
    print(colunas)
    new_row = pd.DataFrame({
        'cluster': [cluster], 
        '2-P': [colunas[0]],              
        '4-V': [colunas[1]],
        '5-E': [colunas[2]],
        '6-D': [colunas[3]],
        '9-SG': [colunas[4]],
    })
    df_cluster = pd.concat([df_cluster, new_row], ignore_index=True)
df_cluster

0
[ 12.66666667   2.66666667   4.66666667  10.66666667 -17.33333333]
1
[27.875  7.75   4.625  5.625  4.625]
2
[31.  8.  7.  3. 13.]
3
[20.5  5.   5.5  7.5 -5.5]
4
[44. 14.  2.  2. 22.]


cluster        2-P        4-V       5-E        6-D       9-SG
0        0  12.666667   2.666667  4.666667  10.666667 -17.333333
1        1  27.875000   7.750000  4.625000   5.625000   4.625000
2        2  31.000000   8.000000  7.000000   3.000000  13.000000
3        3  20.500000   5.000000  5.500000   7.500000  -5.500000
4        4  44.000000  14.000000  2.000000   2.000000  22.000000

In [10]:
df_cluster_sort = df_cluster.sort_values(by='2-P', ascending=False)
df_cluster_sort

cluster        2-P        4-V       5-E        6-D       9-SG
4        4  44.000000  14.000000  2.000000   2.000000  22.000000
2        2  31.000000   8.000000  7.000000   3.000000  13.000000
1        1  27.875000   7.750000  4.625000   5.625000   4.625000
3        3  20.500000   5.000000  5.500000   7.500000  -5.500000
0        0  12.666667   2.666667  4.666667  10.666667 -17.333333

In [11]:
df_cluster_sort['grupo'] = ['Título','Libertadores','Sul-Americana','Limbo','Rebaixamento']
df_cluster_sort

cluster        2-P        4-V       5-E        6-D       9-SG   
4        4  44.000000  14.000000  2.000000   2.000000  22.000000  \
2        2  31.000000   8.000000  7.000000   3.000000  13.000000   
1        1  27.875000   7.750000  4.625000   5.625000   4.625000   
3        3  20.500000   5.000000  5.500000   7.500000  -5.500000   
0        0  12.666667   2.666667  4.666667  10.666667 -17.333333   

           grupo  
4         Título  
2   Libertadores  
1  Sul-Americana  
3          Limbo  
0   Rebaixamento

In [12]:
df_cluster_grupo = df_cluster_sort[['cluster','grupo']]
df_cluster_grupo

cluster          grupo
4        4         Título
2        2   Libertadores
1        1  Sul-Americana
3        3          Limbo
0        0   Rebaixamento

In [13]:
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster
0     PAL   18    8    7    3  33.0  17.0   31  16.0        2
1     AME   18    2    5   11  19.0  40.0   11 -21.0        0
2     CAP   18    8    4    6  26.0  22.0   28   4.0        1
3     BOT   18   14    2    2  32.0  10.0   44  22.0        4
4     RED   18    8    7    3  26.0  16.0   31  10.0        2
5     FOR   18    6    5    7  17.0  19.0   23  -2.0        3
6     CAM   18    6    6    6  21.0  17.0   24   4.0        1
7     COR   18    5    6    7  17.0  20.0   21  -3.0        3
8     FLA   18    9    4    5  30.0  23.0   31   7.0        1
9     GRE   18    9    4    5  26.0  22.0   31   4.0        1
10    FLU   18    9    4    5  24.0  17.0   31   7.0        1
11    CUI   18    8    4    6  21.0  19.0   28   2.0        1
12    SAO   18    7    5    6  23.0  18.0   26   5.0        1
13    CRU   18    6    6    6  19.0  15.0   24   4.0        1
14    INT   18    6    6    6  16.0  20.0   24  -4.0        3
15    VAS   18    3    4   11  13.0  28.0   13 -15.0        0
16    SAN   18    4    6    8  19.0  27.0   18  -8.0        3
17    CFC   18    3    5   10  17.0  33.0   14 -16.0        0
18    GOI   18    5    4    9  17.0  27.0   19 -10.0        3
19    BAH   18    4    6    8  18.0  24.0   18  -6.0        3

In [14]:
tabela_sort = tabela.sort_values(by=['2-P','4-V','9-SG'], ascending=False)
tabela_sort.style.background_gradient(cmap='Blues')
# tabela_sort.style.background_gradient(cmap='Blues').format("{:.2f}").render()


In [15]:
#NORMALIZAR A TABELA E COLORIR...

#grafico com pontuacao original e dos cluster

#grafico dos cluster

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler


In [16]:
df_data = tabela[[
    'cluster',              
    '2-P',              
    '4-V',
    '5-E',
    '6-D',
    '9-SG'
]]

In [17]:
X_Train = df_data.drop(columns=['cluster'], axis=1)
X_Test = df_data.drop(columns=['cluster'], axis=1)
y_Train = df_data['cluster']
y_Test = df_data['cluster']

In [18]:
sc_x = StandardScaler()
X_Train = sc_x.fit_transform(X_Train)
X_Test = sc_x.fit_transform(X_Test)

In [19]:
logreg = LogisticRegression(solver="lbfgs", max_iter=500)
logreg.fit(X_Train, y_Train)
pred_logreg = logreg.predict(X_Test)
pred_proba = logreg.predict_proba(X_Test)

In [20]:
tabela["cluster_pred"] = pred_logreg

In [21]:
lista_proba = pred_proba.tolist()

data = []  # Lista para armazenar os dicionários de dados

index = 0
for proba in lista_proba:
    for i in range(0, len(proba)):
        new_row = {"index": index, "prob": i, "valor": round(proba[i], 4)}
        data.append(new_row)
    index += 1

df_prob = pd.DataFrame(data)  # Cria o DataFrame a partir da lista de dicionários
df_prob = df_prob.pivot_table(
    index="index", columns="prob", values="valor", aggfunc="sum"
)
df_prob = df_prob.reset_index()
df_prob = df_prob.set_index("index")

In [22]:
df_prob = df_prob.rename(columns={
    0.0: 'cl_o',
    1.0: 'cl_1',
    2.0: 'cl_2',
    3.0: 'cl_3',
    4.0: 'cl_4'
})

In [23]:
tabela = pd.merge(tabela, df_prob, left_index=True, right_index=True)
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster  cluster_pred   
0     PAL   18    8    7    3  33.0  17.0   31  16.0        2             2  \
1     AME   18    2    5   11  19.0  40.0   11 -21.0        0             0   
2     CAP   18    8    4    6  26.0  22.0   28   4.0        1             1   
3     BOT   18   14    2    2  32.0  10.0   44  22.0        4             4   
4     RED   18    8    7    3  26.0  16.0   31  10.0        2             2   
5     FOR   18    6    5    7  17.0  19.0   23  -2.0        3             1   
6     CAM   18    6    6    6  21.0  17.0   24   4.0        1             1   
7     COR   18    5    6    7  17.0  20.0   21  -3.0        3             3   
8     FLA   18    9    4    5  30.0  23.0   31   7.0        1             1   
9     GRE   18    9    4    5  26.0  22.0   31   4.0        1             1   
10    FLU   18    9    4    5  24.0  17.0   31   7.0        1             1   
11    CUI   18    8    4    6  21.0  19.0   28   2.0        1             1   
12    SAO   18    7    5    6  23.0  18.0   26   5.0        1             1   
13    CRU   18    6    6    6  19.0  15.0   24   4.0        1             1   
14    INT   18    6    6    6  16.0  20.0   24  -4.0        3             3   
15    VAS   18    3    4   11  13.0  28.0   13 -15.0        0             0   
16    SAN   18    4    6    8  19.0  27.0   18  -8.0        3             3   
17    CFC   18    3    5   10  17.0  33.0   14 -16.0        0             0   
18    GOI   18    5    4    9  17.0  27.0   19 -10.0        3             3   
19    BAH   18    4    6    8  18.0  24.0   18  -6.0        3             3   

      cl_o    cl_1    cl_2    cl_3    cl_4  
0   0.0001  0.2381  0.7068  0.0423  0.0126  
1   0.7578  0.0069  0.0000  0.2353  0.0000  
2   0.0088  0.8072  0.0278  0.1211  0.0352  
3   0.0000  0.3242  0.0141  0.0003  0.6615  
4   0.0003  0.2429  0.6644  0.0802  0.0122  
5   0.0597  0.4589  0.0235  0.4522  0.0056  
6   0.0180  0.4689  0.1091  0.3977  0.0062  
7   0.0694  0.2490  0.0328  0.6471  0.0017  
8   0.0021  0.8212  0.0473  0.0608  0.0686  
9   0.0030  0.8056  0.0446  0.0813  0.0655  
10  0.0021  0.8212  0.0473  0.0608  0.0686  
11  0.0111  0.7844  0.0263  0.1447  0.0336  
12  0.0124  0.6875  0.0624  0.2211  0.0167  
13  0.0180  0.4689  0.1091  0.3977  0.0062  
14  0.0335  0.3059  0.0639  0.5929  0.0038  
15  0.7536  0.0281  0.0001  0.2181  0.0000  
16  0.1706  0.1098  0.0084  0.7109  0.0004  
17  0.5728  0.0289  0.0003  0.3979  0.0000  
18  0.3480  0.2099  0.0014  0.4393  0.0012  
19  0.1585  0.1326  0.0104  0.6981  0.0005

In [24]:
df_pred = tabela[[
    '1-Time',
    'cl_o',
    'cl_1',
    'cl_2',
    'cl_3',
    'cl_4',
]]
df_pred = df_pred.copy()
df_pred

1-Time    cl_o    cl_1    cl_2    cl_3    cl_4
0     PAL  0.0001  0.2381  0.7068  0.0423  0.0126
1     AME  0.7578  0.0069  0.0000  0.2353  0.0000
2     CAP  0.0088  0.8072  0.0278  0.1211  0.0352
3     BOT  0.0000  0.3242  0.0141  0.0003  0.6615
4     RED  0.0003  0.2429  0.6644  0.0802  0.0122
5     FOR  0.0597  0.4589  0.0235  0.4522  0.0056
6     CAM  0.0180  0.4689  0.1091  0.3977  0.0062
7     COR  0.0694  0.2490  0.0328  0.6471  0.0017
8     FLA  0.0021  0.8212  0.0473  0.0608  0.0686
9     GRE  0.0030  0.8056  0.0446  0.0813  0.0655
10    FLU  0.0021  0.8212  0.0473  0.0608  0.0686
11    CUI  0.0111  0.7844  0.0263  0.1447  0.0336
12    SAO  0.0124  0.6875  0.0624  0.2211  0.0167
13    CRU  0.0180  0.4689  0.1091  0.3977  0.0062
14    INT  0.0335  0.3059  0.0639  0.5929  0.0038
15    VAS  0.7536  0.0281  0.0001  0.2181  0.0000
16    SAN  0.1706  0.1098  0.0084  0.7109  0.0004
17    CFC  0.5728  0.0289  0.0003  0.3979  0.0000
18    GOI  0.3480  0.2099  0.0014  0.4393  0.0012
19    BAH  0.1585  0.1326  0.0104  0.6981  0.0005

In [25]:
df_pred.style.background_gradient(cmap='Blues', axis=1)

In [26]:
rodadas = brasileirao['Rodada'].unique()
times = brasileirao['Mandante'].unique()
pontuacao = pd.DataFrame()
data = []  # Lista para armazenar os dicionários de dados

for rodada in rodadas:
    for time in times:
        resultado = brasileirao[(brasileirao['Rodada'] == rodada) & ((brasileirao['Mandante'] == time) | (brasileirao['Visitante'] == time))]
        if len(resultado) > 0:
            resultado = resultado.reset_index()
            if resultado['Mandante'][0] == time:
                if resultado['Score_m'][0] > resultado['Score_v'][0]:
                    pontos = 3
                elif resultado['Score_m'][0] == resultado['Score_v'][0]:
                    pontos = 1
                else:
                    pontos = 0
            else:                  
                if resultado['Score_v'][0] > resultado['Score_m'][0]:
                    pontos = 3
                elif resultado['Score_v'][0] == resultado['Score_m'][0]:
                    pontos = 1
                else:
                    pontos = 0
            new_row = {
                'time': time,
                'rodada': rodada,
                'pontos': pontos
            }        
            data.append(new_row)  # Adiciona o dicionário à lista de dados

pontuacao = pd.DataFrame(data)  # Cria o DataFrame a partir da lista de dicionários

pt_pontuacao = pontuacao.pivot_table(index='rodada', columns='time', values='pontos', aggfunc='sum')
pt_pontuacao_cum = pt_pontuacao.cumsum()
pt_pontuacao_cum

time    AME  BAH  BOT  CAM  CAP  CFC  COR  CRU  CUI  FLA  FLU  FOR  GOI  GRE   
rodada                                                                         
1         0    0    3    0    3    0    3    0    0    3    3    1    0    3  \
2         0    0    6    1    3    0    3    3    1    3    6    4    3    3   
3         0    3    9    4    3    1    3    6    1    3    6    7    3    6   
4         0    6   12    4    6    1    4    9    4    3    7    8    3    7   
5         1    6   15    7    9    2    4    9    4    6   10    9    3    7   
6         1    6   15   10   12    2    5   12    4    9   13   10    6    8   
7         4    7   18   13   12    2    5   12    7   12   13   10    7   11   
8         4    7   21   14   12    3    8   13    8   13   13   13    7   14   
9         7    8   21   17   15    3    8   13   11   16   16   14    7   17   
10        8    9   24   18   16    4    9   14   12   19   17   14    8   17   
11        8   12   27   19   16    4   12   14   12   19   18   17   11   20   
12        8   12   30   19   19    4   12   17   12   22   21   20   11   23   
13        9   12   33   20   20    7   12   18   15   25   21   20   11   26   
14        9   13   36   20   20   10   15   21   16   26   24   23   11   26   
15       10   13   39   21   23   11   16   22   19   27   25   23   12   27   
16       11   14   40   21   26   14   17   22   22   28   25   23   15   30   
17       11   15   43   21   27   14   20   23   25   31   28   23   16   31   
18       11   18   44   24   28   14   21   24   28   31   31   23   19   31   

time    INT  PAL  RED  SAN  SAO  VAS  
rodada                                
1         1    3    3    0    0    3  
2         4    4    4    1    3    4  
3         7    7    4    4    4    4  
4         7   10    5    4    7    5  
5         7   13    6    7    8    6  
6         7   14    7   10    9    6  
7         7   15   10   11   12    6  
8        10   16   13   11   15    6  
9        11   19   13   12   15    6  
10       14   22   14   13   15    6  
11       17   22   17   13   18    6  
12       20   22   20   13   18    9  
13       21   23   23   13   21    9  
14       21   24   24   16   22    9  
15       22   25   24   16   25   10  
16       23   28   25   17   25   10  
17       23   31   28   17   26   10  
18       24   31   31   18   26   13

In [27]:
pt_pontuacao_cum = pt_pontuacao_cum.reset_index()
pt_pontuacao_cum

time  rodada  AME  BAH  BOT  CAM  CAP  CFC  COR  CRU  CUI  ...  FLU  FOR  GOI   
0          1    0    0    3    0    3    0    3    0    0  ...    3    1    0  \
1          2    0    0    6    1    3    0    3    3    1  ...    6    4    3   
2          3    0    3    9    4    3    1    3    6    1  ...    6    7    3   
3          4    0    6   12    4    6    1    4    9    4  ...    7    8    3   
4          5    1    6   15    7    9    2    4    9    4  ...   10    9    3   
5          6    1    6   15   10   12    2    5   12    4  ...   13   10    6   
6          7    4    7   18   13   12    2    5   12    7  ...   13   10    7   
7          8    4    7   21   14   12    3    8   13    8  ...   13   13    7   
8          9    7    8   21   17   15    3    8   13   11  ...   16   14    7   
9         10    8    9   24   18   16    4    9   14   12  ...   17   14    8   
10        11    8   12   27   19   16    4   12   14   12  ...   18   17   11   
11        12    8   12   30   19   19    4   12   17   12  ...   21   20   11   
12        13    9   12   33   20   20    7   12   18   15  ...   21   20   11   
13        14    9   13   36   20   20   10   15   21   16  ...   24   23   11   
14        15   10   13   39   21   23   11   16   22   19  ...   25   23   12   
15        16   11   14   40   21   26   14   17   22   22  ...   25   23   15   
16        17   11   15   43   21   27   14   20   23   25  ...   28   23   16   
17        18   11   18   44   24   28   14   21   24   28  ...   31   23   19   

time  GRE  INT  PAL  RED  SAN  SAO  VAS  
0       3    1    3    3    0    0    3  
1       3    4    4    4    1    3    4  
2       6    7    7    4    4    4    4  
3       7    7   10    5    4    7    5  
4       7    7   13    6    7    8    6  
5       8    7   14    7   10    9    6  
6      11    7   15   10   11   12    6  
7      14   10   16   13   11   15    6  
8      17   11   19   13   12   15    6  
9      17   14   22   14   13   15    6  
10     20   17   22   17   13   18    6  
11     23   20   22   20   13   18    9  
12     26   21   23   23   13   21    9  
13     26   21   24   24   16   22    9  
14     27   22   25   24   16   25   10  
15     30   23   28   25   17   25   10  
16     31   23   31   28   17   26   10  
17     31   24   31   31   18   26   13  

[18 rows x 21 columns]

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
colunas = pt_pontuacao_cum.columns
df_regressao = pd.DataFrame()
data_regressao = []  # Lista para armazenar os dicionários de resultados de regressão

for coluna in colunas:
    if coluna != 'rodada':
        X = pt_pontuacao_cum['rodada'].values.reshape(-1, 1)
        y = pt_pontuacao_cum[coluna].values.reshape(-1, 1)
        regressor = LinearRegression()
        regressor.fit(X, y)
        A = regressor.intercept_[0]
        B = regressor.coef_[0][0]
        x = A + (B * 38)
        new_row_regressao = {
            'time': coluna,
            'intercept': round(A, 2),
            'slope': round(B, 2),
            'pontuacao_final': round(x, 2)
        }
        data_regressao.append(new_row_regressao)

df_regressao = pd.DataFrame(data_regressao)
df_regressao.sort_values(by='pontuacao_final', ascending=False)

time  intercept  slope  pontuacao_final
2   BOT       1.20   2.42            93.28
9   FLA      -1.67   1.91            70.80
13  GRE      -0.62   1.86            70.08
16  RED      -1.17   1.71            63.73
15  PAL       3.21   1.59            63.48
10  FLU       1.90   1.54            60.29
18  SAO       0.17   1.56            59.27
4   CAP       0.55   1.52            58.35
8   CUI      -3.51   1.54            55.20
14  INT       0.31   1.41            53.73
3   CAM       0.83   1.39            53.73
11  FOR       1.91   1.33            52.50
7   CRU       1.86   1.28            50.41
6   COR      -0.67   1.11            41.33
17  SAN       1.42   1.00            39.30
12  GOI      -0.45   0.94            35.35
1   BAH       0.15   0.93            35.33
5   CFC      -2.98   0.88            30.27
0   AME      -1.84   0.79            28.20
19  VAS       2.64   0.47            20.52

In [30]:
df_regressao = df_regressao[['time','slope']]
df_regressao

time  slope
0   AME   0.79
1   BAH   0.93
2   BOT   2.42
3   CAM   1.39
4   CAP   1.52
5   CFC   0.88
6   COR   1.11
7   CRU   1.28
8   CUI   1.54
9   FLA   1.91
10  FLU   1.54
11  FOR   1.33
12  GOI   0.94
13  GRE   1.86
14  INT   1.41
15  PAL   1.59
16  RED   1.71
17  SAN   1.00
18  SAO   1.56
19  VAS   0.47

In [31]:
tabela = tabela.merge(df_regressao, left_on='1-Time', right_on='time', how='left')
tabela

1-Time  3-J  4-V  5-E  6-D  7-GP  8-GC  2-P  9-SG  cluster  cluster_pred   
0     PAL   18    8    7    3  33.0  17.0   31  16.0        2             2  \
1     AME   18    2    5   11  19.0  40.0   11 -21.0        0             0   
2     CAP   18    8    4    6  26.0  22.0   28   4.0        1             1   
3     BOT   18   14    2    2  32.0  10.0   44  22.0        4             4   
4     RED   18    8    7    3  26.0  16.0   31  10.0        2             2   
5     FOR   18    6    5    7  17.0  19.0   23  -2.0        3             1   
6     CAM   18    6    6    6  21.0  17.0   24   4.0        1             1   
7     COR   18    5    6    7  17.0  20.0   21  -3.0        3             3   
8     FLA   18    9    4    5  30.0  23.0   31   7.0        1             1   
9     GRE   18    9    4    5  26.0  22.0   31   4.0        1             1   
10    FLU   18    9    4    5  24.0  17.0   31   7.0        1             1   
11    CUI   18    8    4    6  21.0  19.0   28   2.0        1             1   
12    SAO   18    7    5    6  23.0  18.0   26   5.0        1             1   
13    CRU   18    6    6    6  19.0  15.0   24   4.0        1             1   
14    INT   18    6    6    6  16.0  20.0   24  -4.0        3             3   
15    VAS   18    3    4   11  13.0  28.0   13 -15.0        0             0   
16    SAN   18    4    6    8  19.0  27.0   18  -8.0        3             3   
17    CFC   18    3    5   10  17.0  33.0   14 -16.0        0             0   
18    GOI   18    5    4    9  17.0  27.0   19 -10.0        3             3   
19    BAH   18    4    6    8  18.0  24.0   18  -6.0        3             3   

      cl_o    cl_1    cl_2    cl_3    cl_4 time  slope  
0   0.0001  0.2381  0.7068  0.0423  0.0126  PAL   1.59  
1   0.7578  0.0069  0.0000  0.2353  0.0000  AME   0.79  
2   0.0088  0.8072  0.0278  0.1211  0.0352  CAP   1.52  
3   0.0000  0.3242  0.0141  0.0003  0.6615  BOT   2.42  
4   0.0003  0.2429  0.6644  0.0802  0.0122  RED   1.71  
5   0.0597  0.4589  0.0235  0.4522  0.0056  FOR   1.33  
6   0.0180  0.4689  0.1091  0.3977  0.0062  CAM   1.39  
7   0.0694  0.2490  0.0328  0.6471  0.0017  COR   1.11  
8   0.0021  0.8212  0.0473  0.0608  0.0686  FLA   1.91  
9   0.0030  0.8056  0.0446  0.0813  0.0655  GRE   1.86  
10  0.0021  0.8212  0.0473  0.0608  0.0686  FLU   1.54  
11  0.0111  0.7844  0.0263  0.1447  0.0336  CUI   1.54  
12  0.0124  0.6875  0.0624  0.2211  0.0167  SAO   1.56  
13  0.0180  0.4689  0.1091  0.3977  0.0062  CRU   1.28  
14  0.0335  0.3059  0.0639  0.5929  0.0038  INT   1.41  
15  0.7536  0.0281  0.0001  0.2181  0.0000  VAS   0.47  
16  0.1706  0.1098  0.0084  0.7109  0.0004  SAN   1.00  
17  0.5728  0.0289  0.0003  0.3979  0.0000  CFC   0.88  
18  0.3480  0.2099  0.0014  0.4393  0.0012  GOI   0.94  
19  0.1585  0.1326  0.0104  0.6981  0.0005  BAH   0.93

In [32]:
from sklearn.cluster import KMeans
df_data = tabela[[
    '2-P',              
    '4-V',
    '5-E',
    '6-D',
    '9-SG',
    'slope'
]]
kmeans = KMeans(n_clusters=5, random_state=0).fit(df_data)
tabela['cluster'] = kmeans.labels_
tabela['c_p'] = kmeans.cluster_centers_[kmeans.labels_,0]
tabela['c_v'] = kmeans.cluster_centers_[kmeans.labels_,1]
tabela['c_e'] = kmeans.cluster_centers_[kmeans.labels_,2]
tabela['c_d'] = kmeans.cluster_centers_[kmeans.labels_,3]
tabela['c_sg'] = kmeans.cluster_centers_[kmeans.labels_,4]
tabela['c_slope'] = kmeans.cluster_centers_[kmeans.labels_,5]
tabela_sort = tabela.sort_values(by=['2-P','4-V','9-SG'], ascending=False)
tabela_sort.style.background_gradient(cmap='Blues')


c:\Python310\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [33]:
pontuacao_2 = pt_pontuacao_cum[pt_pontuacao_cum['rodada'] > 19]
pontuacao_2

time  rodada  AME  BAH  BOT  CAM  CAP  CFC  COR  CRU  CUI  ...  FLU  FOR  GOI   
9         10    8    9   24   18   16    4    9   14   12  ...   17   14    8  \
10        11    8   12   27   19   16    4   12   14   12  ...   18   17   11   
11        12    8   12   30   19   19    4   12   17   12  ...   21   20   11   
12        13    9   12   33   20   20    7   12   18   15  ...   21   20   11   
13        14    9   13   36   20   20   10   15   21   16  ...   24   23   11   
14        15   10   13   39   21   23   11   16   22   19  ...   25   23   12   
15        16   11   14   40   21   26   14   17   22   22  ...   25   23   15   
16        17   11   15   43   21   27   14   20   23   25  ...   28   23   16   
17        18   11   18   44   24   28   14   21   24   28  ...   31   23   19   

time  GRE  INT  PAL  RED  SAN  SAO  VAS  
9      17   14   22   14   13   15    6  
10     20   17   22   17   13   18    6  
11     23   20   22   20   13   18    9  
12     26   21   23   23   13   21    9  
13     26   21   24   24   16   22    9  
14     27   22   25   24   16   25   10  
15     30   23   28   25   17   25   10  
16     31   23   31   28   17   26   10  
17     31   24   31   31   18   26   13  

[9 rows x 21 columns]

In [34]:
colunas = pontuacao_2.columns
df_regressao = pd.DataFrame()
colunas = pontuacao_2.columns
regressao_data = []

for coluna in colunas:
    if coluna != 'rodada':
        X = pontuacao_2['rodada'].values.reshape(-1, 1)
        y = pontuacao_2[coluna].values.reshape(-1, 1)
        regressor = LinearRegression()
        regressor.fit(X, y)
        A = regressor.intercept_[0]
        B = regressor.coef_[0][0]
        x = A + (B * 38)
        regressao_data.append({
            'time': coluna,
            'intercept': round(A, 2),
            'slope': round(B, 2),
            'pontuacao_final': round(x, 2)
        })

df_regressao = pd.DataFrame(regressao_data)
df_regressao.sort_values(by='pontuacao_final', ascending=False)

time  intercept  slope  pontuacao_final
2   BOT      -0.82   2.57            96.71
8   CUI     -11.74   2.12            68.69
16  RED      -3.24   1.87            67.69
13  GRE       1.40   1.73            67.27
9   FLA       2.47   1.63            64.53
10  FLU       0.47   1.63            62.53
4   CAP      -1.20   1.63            60.87
18  SAO       1.71   1.43            56.18
15  PAL       7.37   1.28            56.13
7   CRU       0.54   1.35            51.84
6   COR      -5.18   1.43            49.29
5   CFC     -12.82   1.57            46.71
14  INT       5.39   1.08            46.56
11  FOR       5.97   1.05            45.87
12  GOI      -3.20   1.13            39.87
3   CAM      12.17   0.58            34.33
1   BAH       1.44   0.83            33.11
17  SAN       5.08   0.72            32.31
19  VAS      -0.92   0.72            26.31
0   AME       2.91   0.47            20.64